#pragma once
#include <cstdint>
#include <memory>
#include <stdexcept>
#include "rust/cxx.h"
#include "hll.hpp"
#include "hll.rs.h" // generated by cxx from src/hll.rs (Task 4)

namespace apache_datasketches_rs {

datasketches::target_hll_type to_cpp_target_type(TargetHllType t);
TargetHllType to_rust_target_type(datasketches::target_hll_type t);

class HllSketchShim {
public:
  explicit HllSketchShim(uint8_t lg_config_k, TargetHllType tgt_type);
  explicit HllSketchShim(datasketches::hll_sketch sketch);

  void update_u64(uint64_t value);
  void update_i64(int64_t value);
  void update_f64(double value);
  void update_str(rust::Str value);
  void update_bytes(rust::Slice<const uint8_t> value);

  double get_estimate() const;
  double get_lower_bound(uint8_t num_std_dev) const;
  double get_upper_bound(uint8_t num_std_dev) const;
  uint8_t get_lg_config_k() const;
  TargetHllType get_target_type() const;
  bool is_empty() const;
  void reset();
  rust::String to_string_summary() const;

  rust::Vec<uint8_t> serialize_compact() const;
  rust::Vec<uint8_t> serialize_updatable() const;

  const datasketches::hll_sketch& inner() const { return sketch_; }

private:
  datasketches::hll_sketch sketch_;
};

std::unique_ptr<HllSketchShim> new_hll_sketch(uint8_t lg_config_k, TargetHllType tgt_type);
std::unique_ptr<HllSketchShim> hll_sketch_copy_as(const HllSketchShim& sketch, TargetHllType tgt_type);
std::unique_ptr<HllSketchShim> hll_sketch_deserialize(rust::Slice<const uint8_t> bytes);

} // namespace apache_datasketches_rs
