#pragma once
#include <cstdint>
#include <memory>
#include <vector>
#include <stdexcept>
#include "rust/cxx.h"
#include "hll.hpp"

namespace apache_datasketches_rs {

// Forward declaration matching the enum generated by cxx from src/hll.rs
// (Task 4). We deliberately do NOT `#include "hll.rs.h"` here: that
// generated header itself starts with `#include "hll_sketch_shim.h"` (from
// the bridge's `include!` directive), which would re-enter this header
// while it's still being processed (blocked by `#pragma once`) and leave
// `HllSketchShim` undefined when `hll.rs.h` later aliases it. An opaque
// enum declaration with a fixed underlying type is a complete type usable
// in function signatures, so this forward declaration is sufficient here;
// the full enum definition (needed to switch over its values) is pulled in
// by hll_sketch_shim.cc via `#include "hll.rs.h"` after this header.
enum class TargetHllType : std::uint8_t;

datasketches::target_hll_type to_cpp_target_type(TargetHllType t);
TargetHllType to_rust_target_type(datasketches::target_hll_type t);

class HllSketchShim {
public:
  explicit HllSketchShim(uint8_t lg_config_k, TargetHllType tgt_type);
  explicit HllSketchShim(datasketches::hll_sketch sketch);

  void update_u64(uint64_t value);
  void update_i64(int64_t value);
  void update_f64(double value);
  void update_str(rust::Str value);
  void update_bytes(rust::Slice<const uint8_t> value);

  double get_estimate() const;
  double get_lower_bound(uint8_t num_std_dev) const;
  double get_upper_bound(uint8_t num_std_dev) const;
  uint8_t get_lg_config_k() const;
  TargetHllType get_target_type() const;
  bool is_empty() const;
  void reset();
  rust::String to_string_summary() const;

  std::unique_ptr<std::vector<uint8_t>> serialize_compact() const;
  std::unique_ptr<std::vector<uint8_t>> serialize_updatable() const;

  const datasketches::hll_sketch& inner() const { return sketch_; }

private:
  datasketches::hll_sketch sketch_;
};

std::unique_ptr<HllSketchShim> new_hll_sketch(uint8_t lg_config_k, TargetHllType tgt_type);
std::unique_ptr<HllSketchShim> hll_sketch_copy_as(const HllSketchShim& sketch, TargetHllType tgt_type);
std::unique_ptr<HllSketchShim> hll_sketch_deserialize(rust::Slice<const uint8_t> bytes);

} // namespace apache_datasketches_rs
