#include "hll_sketch_shim.h"
#include "hll.rs.h" // generated by cxx from src/hll.rs (Task 4); provides the full TargetHllType enum definition
#include <vector>

namespace apache_datasketches_rs {

datasketches::target_hll_type to_cpp_target_type(TargetHllType t) {
  switch (t) {
    case TargetHllType::Hll4: return datasketches::HLL_4;
    case TargetHllType::Hll6: return datasketches::HLL_6;
    case TargetHllType::Hll8: return datasketches::HLL_8;
    default: throw std::invalid_argument("unknown TargetHllType");
  }
}

TargetHllType to_rust_target_type(datasketches::target_hll_type t) {
  switch (t) {
    case datasketches::HLL_4: return TargetHllType::Hll4;
    case datasketches::HLL_6: return TargetHllType::Hll6;
    case datasketches::HLL_8: return TargetHllType::Hll8;
    default: throw std::invalid_argument("unknown target_hll_type");
  }
}

HllSketchShim::HllSketchShim(uint8_t lg_config_k, TargetHllType tgt_type)
  : sketch_(lg_config_k, to_cpp_target_type(tgt_type)) {}

HllSketchShim::HllSketchShim(datasketches::hll_sketch sketch)
  : sketch_(std::move(sketch)) {}

void HllSketchShim::update_u64(uint64_t value) { sketch_.update(value); }
void HllSketchShim::update_i64(int64_t value) { sketch_.update(value); }
void HllSketchShim::update_f64(double value) { sketch_.update(value); }
void HllSketchShim::update_str(rust::Str value) {
  // Forward the borrowed bytes rather than heap-copying them into a
  // std::string. The empty guard is replicated because it lives in the
  // overload being bypassed, and the pointer overload below it screens on a
  // null pointer rather than on a zero length.
  if (value.empty()) return;
  sketch_.update(value.data(), value.size());
}
void HllSketchShim::update_bytes(rust::Slice<const uint8_t> value) {
  sketch_.update(value.data(), value.size());
}

double HllSketchShim::get_estimate() const { return sketch_.get_estimate(); }
double HllSketchShim::get_lower_bound(uint8_t num_std_dev) const {
  return sketch_.get_lower_bound(num_std_dev);
}
double HllSketchShim::get_upper_bound(uint8_t num_std_dev) const {
  return sketch_.get_upper_bound(num_std_dev);
}
uint8_t HllSketchShim::get_lg_config_k() const { return sketch_.get_lg_config_k(); }
TargetHllType HllSketchShim::get_target_type() const {
  return to_rust_target_type(sketch_.get_target_type());
}
bool HllSketchShim::is_empty() const { return sketch_.is_empty(); }
void HllSketchShim::reset() { sketch_.reset(); }

rust::String HllSketchShim::to_string_summary() const {
  return rust::String(std::string(sketch_.to_string().c_str()));
}

// Returned as a heap std::vector rather than a rust::Vec built by hand.
// rust::Vec::push_back goes through emplace_back, which makes two
// non-inlinable extern "C" calls back into Rust per element; over a
// serialized buffer that is two boundary crossings per byte, and it dominated
// everything else the call does. A unique_ptr hands the buffer over whole and
// leaves the Rust side one memcpy to do.
std::unique_ptr<std::vector<uint8_t>> HllSketchShim::serialize_compact() const {
  return std::make_unique<std::vector<uint8_t>>(sketch_.serialize_compact());
}

std::unique_ptr<std::vector<uint8_t>> HllSketchShim::serialize_updatable() const {
  return std::make_unique<std::vector<uint8_t>>(sketch_.serialize_updatable());
}

std::unique_ptr<HllSketchShim> new_hll_sketch(uint8_t lg_config_k, TargetHllType tgt_type) {
  return std::make_unique<HllSketchShim>(lg_config_k, tgt_type);
}

std::unique_ptr<HllSketchShim> hll_sketch_copy_as(const HllSketchShim& sketch, TargetHllType tgt_type) {
  return std::make_unique<HllSketchShim>(
      datasketches::hll_sketch(sketch.inner(), to_cpp_target_type(tgt_type)));
}

std::unique_ptr<HllSketchShim> hll_sketch_deserialize(rust::Slice<const uint8_t> bytes) {
  return std::make_unique<HllSketchShim>(
      datasketches::hll_sketch::deserialize(bytes.data(), bytes.size()));
}

} // namespace apache_datasketches_rs
