#include "theta_sketch_shim.h"
#include "theta_compact_shim.h"
#include "theta_sketch.rs.h" // generated by cxx from src/theta_sketch.rs (this task); provides the full ResizeFactor enum definition

namespace apache_datasketches_rs {

datasketches::resize_factor to_cpp_resize_factor(ResizeFactor rf) {
  switch (rf) {
    case ResizeFactor::X1: return datasketches::resize_factor::X1;
    case ResizeFactor::X2: return datasketches::resize_factor::X2;
    case ResizeFactor::X4: return datasketches::resize_factor::X4;
    case ResizeFactor::X8: return datasketches::resize_factor::X8;
    default: throw std::invalid_argument("unknown ResizeFactor");
  }
}

namespace {
datasketches::update_theta_sketch build_sketch(uint8_t lg_k, ResizeFactor rf, float p) {
  datasketches::update_theta_sketch::builder builder;
  builder.set_lg_k(lg_k);
  builder.set_resize_factor(to_cpp_resize_factor(rf));
  builder.set_p(p);
  return builder.build();
}
} // namespace

ThetaSketchShim::ThetaSketchShim(uint8_t lg_k, ResizeFactor rf, float p)
  : sketch_(build_sketch(lg_k, rf, p)) {}

ThetaSketchShim::ThetaSketchShim(datasketches::update_theta_sketch sketch)
  : sketch_(std::move(sketch)) {}

void ThetaSketchShim::update_u64(uint64_t value) { sketch_.update(value); }
void ThetaSketchShim::update_i64(int64_t value) { sketch_.update(value); }
void ThetaSketchShim::update_u32(uint32_t value) { sketch_.update(value); }
void ThetaSketchShim::update_i32(int32_t value) { sketch_.update(value); }
void ThetaSketchShim::update_u16(uint16_t value) { sketch_.update(value); }
void ThetaSketchShim::update_i16(int16_t value) { sketch_.update(value); }
void ThetaSketchShim::update_u8(uint8_t value) { sketch_.update(value); }
void ThetaSketchShim::update_i8(int8_t value) { sketch_.update(value); }
void ThetaSketchShim::update_f64(double value) { sketch_.update(value); }
void ThetaSketchShim::update_str(rust::Str value) {
  // Forward the borrowed bytes directly; the empty guard is replicated
  // because it lives in the std::string overload being bypassed.
  if (value.empty()) return;
  sketch_.update(value.data(), value.size());
}
void ThetaSketchShim::update_bytes(rust::Slice<const uint8_t> value) {
  sketch_.update(value.data(), value.size());
}

void ThetaSketchShim::trim() { sketch_.trim(); }
void ThetaSketchShim::reset() { sketch_.reset(); }

double ThetaSketchShim::get_estimate() const { return sketch_.get_estimate(); }
double ThetaSketchShim::get_lower_bound(uint8_t num_std_dev) const {
  return sketch_.get_lower_bound(num_std_dev);
}
double ThetaSketchShim::get_upper_bound(uint8_t num_std_dev) const {
  return sketch_.get_upper_bound(num_std_dev);
}
bool ThetaSketchShim::is_empty() const { return sketch_.is_empty(); }
bool ThetaSketchShim::is_estimation_mode() const { return sketch_.is_estimation_mode(); }
bool ThetaSketchShim::is_ordered() const { return sketch_.is_ordered(); }
double ThetaSketchShim::get_theta() const { return sketch_.get_theta(); }
uint32_t ThetaSketchShim::get_num_retained() const { return sketch_.get_num_retained(); }

std::unique_ptr<ThetaSketchShim> new_theta_sketch(uint8_t lg_k, ResizeFactor rf, float p) {
  return std::make_unique<ThetaSketchShim>(lg_k, rf, p);
}

std::unique_ptr<CompactThetaSketchShim> ThetaSketchShim::compact(bool ordered) const {
  return theta_sketch_compact(*this, ordered);
}

} // namespace apache_datasketches_rs
