#pragma once
#include <cstdint>
#include <memory>
#include <stdexcept>
#include "rust/cxx.h"
#include "theta_sketch.hpp"

namespace apache_datasketches_rs {

// Forward declarations
class CompactThetaSketchShim;

// Forward declaration matching the enum generated by cxx from src/theta_sketch.rs
// (this task). We deliberately do NOT `#include "theta_sketch.rs.h"` here, for
// the same reason documented in HLL's hll_sketch_shim.h: the generated header's
// own `include!` directive re-enters this header while it's still being
// processed. The full enum definition is pulled in by theta_sketch_shim.cc via
// `#include "theta_sketch.rs.h"` after this header.
enum class ResizeFactor : std::uint8_t;

datasketches::resize_factor to_cpp_resize_factor(ResizeFactor rf);

class ThetaSketchShim {
public:
  explicit ThetaSketchShim(uint8_t lg_k, ResizeFactor rf, float p);
  explicit ThetaSketchShim(datasketches::update_theta_sketch sketch);

  void update_u64(uint64_t value);
  void update_i64(int64_t value);
  void update_u32(uint32_t value);
  void update_i32(int32_t value);
  void update_u16(uint16_t value);
  void update_i16(int16_t value);
  void update_u8(uint8_t value);
  void update_i8(int8_t value);
  void update_f64(double value);
  void update_str(rust::Str value);
  void update_bytes(rust::Slice<const uint8_t> value);

  void trim();
  void reset();

  double get_estimate() const;
  double get_lower_bound(uint8_t num_std_dev) const;
  double get_upper_bound(uint8_t num_std_dev) const;
  bool is_empty() const;
  bool is_estimation_mode() const;
  bool is_ordered() const;
  double get_theta() const;
  uint32_t get_num_retained() const;
  std::unique_ptr<CompactThetaSketchShim> compact(bool ordered) const;

  const datasketches::update_theta_sketch& inner() const { return sketch_; }

private:
  datasketches::update_theta_sketch sketch_;
};

std::unique_ptr<ThetaSketchShim> new_theta_sketch(uint8_t lg_k, ResizeFactor rf, float p);

} // namespace apache_datasketches_rs
