#include "array_of_doubles_sketch_shim.h"
#include "array_of_doubles_compact_shim.h"
#include "array_of_doubles_sketch.rs.h" // generated by cxx from src/array_of_doubles_sketch.rs; provides the full TupleResizeFactor enum definition

namespace apache_datasketches_rs {

datasketches::resize_factor to_cpp_tuple_resize_factor(TupleResizeFactor rf) {
  switch (rf) {
    case TupleResizeFactor::X1: return datasketches::resize_factor::X1;
    case TupleResizeFactor::X2: return datasketches::resize_factor::X2;
    case TupleResizeFactor::X4: return datasketches::resize_factor::X4;
    case TupleResizeFactor::X8: return datasketches::resize_factor::X8;
    default: throw std::invalid_argument("unknown TupleResizeFactor");
  }
}

namespace {

// The builder's single constructor argument is the update policy, which is
// what carries num_values. lg_k/resize_factor/p validation is inherited from
// theta_base_builder and throws std::invalid_argument, which cxx turns into
// Result::Err on the Rust side.
datasketches::update_array_of_doubles_sketch build_sketch(uint8_t lg_k, TupleResizeFactor rf, float p, uint8_t num_values) {
  datasketches::update_array_of_doubles_sketch::builder builder{
      datasketches::default_array_of_doubles_update_policy(num_values)};
  builder.set_lg_k(lg_k);
  builder.set_resize_factor(to_cpp_tuple_resize_factor(rf));
  builder.set_p(p);
  return builder.build();
}

// Upstream's default_array_tuple_update_policy indexes the supplied value
// blindly for i in [0, num_values), with no bounds check of its own. The safe
// Rust wrapper rejects a wrong-length slice before it ever gets here; this is
// a second line of defence for direct sys-crate callers.
void check_values_len(const datasketches::update_array_of_doubles_sketch& sketch, rust::Slice<const double> values) {
  if (values.size() != sketch.get_num_values()) {
    throw std::invalid_argument("values length does not match num_values");
  }
}

std::vector<double> to_vector(rust::Slice<const double> values) {
  return std::vector<double>(values.begin(), values.end());
}

} // namespace

ArrayOfDoublesSketchShim::ArrayOfDoublesSketchShim(uint8_t lg_k, TupleResizeFactor rf, float p, uint8_t num_values)
  : sketch_(build_sketch(lg_k, rf, p, num_values)) {}

void ArrayOfDoublesSketchShim::update_u64(uint64_t key, rust::Slice<const double> values) {
  check_values_len(sketch_, values);
  sketch_.update(key, to_vector(values));
}
void ArrayOfDoublesSketchShim::update_i64(int64_t key, rust::Slice<const double> values) {
  check_values_len(sketch_, values);
  sketch_.update(key, to_vector(values));
}
void ArrayOfDoublesSketchShim::update_u32(uint32_t key, rust::Slice<const double> values) {
  check_values_len(sketch_, values);
  sketch_.update(key, to_vector(values));
}
void ArrayOfDoublesSketchShim::update_i32(int32_t key, rust::Slice<const double> values) {
  check_values_len(sketch_, values);
  sketch_.update(key, to_vector(values));
}
void ArrayOfDoublesSketchShim::update_u16(uint16_t key, rust::Slice<const double> values) {
  check_values_len(sketch_, values);
  sketch_.update(key, to_vector(values));
}
void ArrayOfDoublesSketchShim::update_i16(int16_t key, rust::Slice<const double> values) {
  check_values_len(sketch_, values);
  sketch_.update(key, to_vector(values));
}
void ArrayOfDoublesSketchShim::update_u8(uint8_t key, rust::Slice<const double> values) {
  check_values_len(sketch_, values);
  sketch_.update(key, to_vector(values));
}
void ArrayOfDoublesSketchShim::update_i8(int8_t key, rust::Slice<const double> values) {
  check_values_len(sketch_, values);
  sketch_.update(key, to_vector(values));
}
void ArrayOfDoublesSketchShim::update_f64(double key, rust::Slice<const double> values) {
  check_values_len(sketch_, values);
  sketch_.update(key, to_vector(values));
}
void ArrayOfDoublesSketchShim::update_str(rust::Str key, rust::Slice<const double> values) {
  check_values_len(sketch_, values);
  sketch_.update(std::string(key), to_vector(values));
}
void ArrayOfDoublesSketchShim::update_bytes(rust::Slice<const uint8_t> key, rust::Slice<const double> values) {
  check_values_len(sketch_, values);
  sketch_.update(key.data(), key.size(), to_vector(values));
}

void ArrayOfDoublesSketchShim::trim() { sketch_.trim(); }
void ArrayOfDoublesSketchShim::reset() { sketch_.reset(); }

double ArrayOfDoublesSketchShim::get_estimate() const { return sketch_.get_estimate(); }
double ArrayOfDoublesSketchShim::get_lower_bound(uint8_t num_std_dev) const {
  return sketch_.get_lower_bound(num_std_dev);
}
double ArrayOfDoublesSketchShim::get_upper_bound(uint8_t num_std_dev) const {
  return sketch_.get_upper_bound(num_std_dev);
}
bool ArrayOfDoublesSketchShim::is_empty() const { return sketch_.is_empty(); }
bool ArrayOfDoublesSketchShim::is_estimation_mode() const { return sketch_.is_estimation_mode(); }
bool ArrayOfDoublesSketchShim::is_ordered() const { return sketch_.is_ordered(); }
double ArrayOfDoublesSketchShim::get_theta() const { return sketch_.get_theta(); }
uint32_t ArrayOfDoublesSketchShim::get_num_retained() const { return sketch_.get_num_retained(); }
uint8_t ArrayOfDoublesSketchShim::get_num_values() const { return sketch_.get_num_values(); }

rust::Vec<uint64_t> ArrayOfDoublesSketchShim::entry_hashes() const {
  rust::Vec<uint64_t> out;
  for (const auto& entry : sketch_) out.push_back(entry.first);
  return out;
}

rust::Vec<double> ArrayOfDoublesSketchShim::entry_values() const {
  rust::Vec<double> out;
  for (const auto& entry : sketch_) {
    for (uint8_t i = 0; i < entry.second.size(); ++i) out.push_back(entry.second[i]);
  }
  return out;
}

std::unique_ptr<ArrayOfDoublesSketchShim> new_array_of_doubles_sketch(uint8_t lg_k, TupleResizeFactor rf, float p, uint8_t num_values) {
  return std::make_unique<ArrayOfDoublesSketchShim>(lg_k, rf, p, num_values);
}

std::unique_ptr<CompactArrayOfDoublesSketchShim> ArrayOfDoublesSketchShim::compact(bool ordered) const {
  return array_of_doubles_sketch_compact(*this, ordered);
}

} // namespace apache_datasketches_rs
