#[cfg(feature = "hll")]
pub mod hll;

#[cfg(feature = "theta")]
pub mod theta_a_not_b;
#[cfg(feature = "theta")]
pub mod theta_compact;
#[cfg(feature = "theta")]
pub mod theta_input;
#[cfg(feature = "theta")]
pub mod theta_intersection;
#[cfg(feature = "theta")]
pub mod theta_jaccard;
#[cfg(feature = "theta")]
pub mod theta_sketch;
#[cfg(feature = "theta")]
pub mod theta_union;
#[cfg(feature = "theta")]
pub mod theta_wrapped;

#[cfg(feature = "cpc")]
pub mod cpc_sketch;
#[cfg(feature = "cpc")]
pub mod cpc_union;

#[cfg(feature = "tuple")]
pub mod array_of_doubles_a_not_b;
#[cfg(feature = "tuple")]
pub mod array_of_doubles_compact;
#[cfg(feature = "tuple")]
pub mod array_of_doubles_input;
#[cfg(feature = "tuple")]
pub mod array_of_doubles_intersection;
#[cfg(feature = "tuple")]
pub mod array_of_doubles_jaccard;
#[cfg(feature = "tuple")]
pub mod array_of_doubles_sketch;
#[cfg(feature = "tuple")]
pub mod array_of_doubles_union;
#[cfg(feature = "tuple")]
pub mod tuple_generic;
#[cfg(feature = "tuple")]
pub mod tuple_generic_a_not_b;
#[cfg(feature = "tuple")]
pub mod tuple_generic_input;
#[cfg(feature = "tuple")]
pub mod tuple_generic_intersection;
#[cfg(feature = "tuple")]
pub mod tuple_generic_jaccard;
#[cfg(feature = "tuple")]
pub mod tuple_generic_union;
